name: Transform Tokens

on:
  push:
    branches:
      - design
    paths:
      - 'token/token.json'  
  
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  transform-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.FIGMA_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Token Transformer
        run: |
            npx token-transformer token/token.json token/token-tf.json global
            git config --global user.name "curomame"
            git config --global user.email "curomame@naver.com"
            git add .
            git commit -m 'token updated'
            git push
        env:
            GITHUB_TOKEN: ${{ secrets.FIGMA_TOKEN }}

      - name: Run transform script
        run: node ./token/token_tf.mjs

      - name: Delete existing branch
        run: |
          git fetch origin
          git branch -r | grep -q "origin/transform-tokens-branch" && git push origin --delete transform-tokens-branch || echo "Branch does not exist"
        continue-on-error: true

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.FIGMA_TOKEN }}
          commit-message: Transform tokens and update styles
          branch: transform-tokens-branch
          title: "Transform tokens and update styles"
          body: "This PR transforms tokens and updates styles automatically."
          base: master
          delete-branch: true
          force: true

      - name: Auto-merge Pull Request
        if: steps.create-pr.outputs.pull-request-number
        run: |
          PR_NUMBER="${{ steps.create-pr.outputs.pull-request-number }}"
          gh pr merge $PR_NUMBER --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.FIGMA_TOKEN }}